### ISSUE TITLE
clientManipulator construct error

### ISSUE THREAD

**Issue by slmcncb** [GeniusesOfSymfony/WebSocketBundle#113]
**ChatTopic.php**
```php
<?php

namespace AppBundle\Topic;

use Gos\Bundle\WebSocketBundle\Topic\TopicInterface;
use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimer;
use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimerInterface;
use Gos\Bundle\WebSocketBundle\Client\ClientManipulatorInterface;
use Gos\Bundle\WebSocketBundle\Router\WampRequest;
use Ratchet\ConnectionInterface;
use Ratchet\Wamp\Topic;


class ChatTopic implements TopicInterface, TopicPeriodicTimerInterface
{

    protected $clientManipulator;
    
    public function __construct(ClientManipulatorInterface $clientManipulator)
    {
        $this->clientManipulator = $clientManipulator;
    }

...
```

**"php app/console gos:websocket:server" output:**
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to AppBundle\Topic\ChatTopic::__construct() must be an instance of Gos\Bundle\WebSocketBundle\Client\ClientManipulatorInterface, none given, called in /home/admin/web/dev.scc/public_html/socket/app/cache/dev/appDevDebugProjectContainer.php on line 383 in /home/admin/web/dev.scc/public_html/socket/src/AppBundle/Topic/ChatTopic.php:19
Stack trace:
#0 /home/admin/web/dev.scc/public_html/socket/app/cache/dev/appDevDebugProjectContainer.php(383): AppBundle\Topic\ChatTopic->__construct()
#1 /home/admin/web/dev.scc/public_html/socket/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(316): appDevDebugProjectContainer->getApp_TopicChatServiceService()
#2 /home/admin/web/dev.scc/public_html/socket/app/cache/dev/appDevDebugProjectContainer.php(2299): Symfony\Component\DependencyInjection\Container->get('app.topic_chat_...')
#3 /home/admin/web/dev.scc/public_html/socket/vendor/symfony/symfony/src/Sym in /home/admin/web/dev.scc/public_html/socket/src/AppBundle/Topic/ChatTopic.php on line 19

```

PHP 7.0.3
Symfony 2.8.3
WebSocketBundle 1.6.4

**Comment by cristhianfernandez01** [comment]
Hello, this error is because it is perhaps not injected the ClientManipulator class in the service definition for your ChatTopic class. You would have to have something like the following in your services.yml file: 
```
app.chat_topic:
        class: AppBundle\Topic\ChatTopic
        arguments: [@gos_web_socket.websocket.client_manipulator]
```

I hope I've been helpful. Cheers

**Comment by slmcncb** [comment]
@cristhianfernandez01 Thanks. I did not see the [document](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md#retrieve-authenticated-user).
