### ISSUE TITLE
Securing topic against execption (now forwarded into websocket instead of crash) 

### ISSUE THREAD

**Issue by KrissMcCone** [GeniusesOfSymfony/WebSocketBundle#23]
Hello before this commit when there was some error in topic(e.g. undefineded index in array), server crashed and showed the error. Now nothing is showed, just brodcast method doesnt' work. What does it mean forwarded into websocket? Cos i see nothing in console. Did you add automatic brodcast message that we send to the websocket? Can I turn off it?

**Comment by ProPheT777** [comment]
Fixed in 7bfb8787ca42d4e10ad6de34c32fe5773186cd87

**Comment by KrissMcCone** [comment]
Works, thanks.
```
[2015-05-26 14:15:21] websocket.ERROR: Notice: Undefined index: xdxd {"code":0,"file":"/Applications/XAMPP/xamppfiles/htdocs/app/src/app/ChatBundle/Topic/ChatTopic.php","trace":"#0 /Applications/XAMPP/xamppfiles/htdocs/app/src/app/ChatBundle/Topic/ChatTopic.php(123): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined index...', '/Applications/X...', 123, Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php(107): app\\ChatBundle\\Topic\\ChatTopic->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php(80): Gos\\Bundle\\WebSocketBundle\\Server\\App\\Dispatcher\\TopicDispatcher->dispatch('onPublish', Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/WampApplication.php(99): Gos\\Bundle\\WebSocketBundle\\Server\\App\\Dispatcher\\TopicDispatcher->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#4 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/TopicManager.php(70): Gos\\Bundle\\WebSocketBundle\\Server\\App\\WampApplication->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Array, Array, Array)\n#5 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/ServerProtocol.php(133): Ratchet\\Wamp\\TopicManager->onPublish(Object(Ratchet\\Wamp\\WampConnection), 'chat/90/e4de45f...', Array, Array, Array)\n#6 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/WampServer.php(41): Ratchet\\Wamp\\ServerProtocol->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#7 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Session/SessionProvider.php(94): Ratchet\\Wamp\\WampServer->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#8 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/WebSocket/Version/RFC6455.php(202): Ratchet\\Session\\SessionProvider->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#9 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(96): Ratchet\\WebSocket\\Version\\RFC6455->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#10 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(53): Ratchet\\WebSocket\\WsServer->onMessage(Object(Ratchet\\Server\\IoConnection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#11 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(113): Ratchet\\Http\\HttpServer->onMessage(Object(Ratchet\\Server\\IoConnection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#12 [internal function]: Ratchet\\Server\\IoServer->handleData('\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...', Object(React\\Socket\\Connection))\n#13 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)\n#14 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/socket/src/Connection.php(15): Evenement\\EventEmitter->emit('data', Array)\n#15 [internal function]: React\\Socket\\Connection->handleData(Resource id #485, Object(React\\EventLoop\\StreamSelectLoop))\n#16 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/event-loop/StreamSelectLoop.php(227): call_user_func(Array, Resource id #485, Object(React\\EventLoop\\StreamSelectLoop))\n#17 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/event-loop/StreamSelectLoop.php(201): React\\EventLoop\\StreamSelectLoop->waitForStreamActivity(5000000)\n#18 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/Type/WebSocketServer.php(192): React\\EventLoop\\StreamSelectLoop->run()\n#19 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/EntryPoint.php(48): Gos\\Bundle\\WebSocketBundle\\Server\\Type\\WebSocketServer->launch()\n#20 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Command/WebsocketServerCommand.php(51): Gos\\Bundle\\WebSocketBundle\\Server\\EntryPoint->launch(NULL)\n#21 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(257): Gos\\Bundle\\WebSocketBundle\\Command\\WebsocketServerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(882): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Gos\\Bundle\\WebSocketBundle\\Command\\WebsocketServerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#24 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#25 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#26 /Applications/XAMPP/xamppfiles/htdocs/app/app/console(27): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput))\n#27 {main}"} 
[2015-05-26 14:15:21] websocket.ERROR: Notice: Undefined index: xdxd {"code":0,"file":"/Applications/XAMPP/xamppfiles/htdocs/app/src/app/ChatBundle/Topic/ChatTopic.php","trace":"#0 /Applications/XAMPP/xamppfiles/htdocs/app/src/app/ChatBundle/Topic/ChatTopic.php(123): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined index...', '/Applications/X...', 123, Array)\n#1 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php(107): app\\ChatBundle\\Topic\\ChatTopic->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#2 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/Dispatcher/TopicDispatcher.php(80): Gos\\Bundle\\WebSocketBundle\\Server\\App\\Dispatcher\\TopicDispatcher->dispatch('onPublish', Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#3 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/App/WampApplication.php(99): Gos\\Bundle\\WebSocketBundle\\Server\\App\\Dispatcher\\TopicDispatcher->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Object(Gos\\Bundle\\WebSocketBundle\\Router\\WampRequest), Array, Array, Array)\n#4 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/TopicManager.php(70): Gos\\Bundle\\WebSocketBundle\\Server\\App\\WampApplication->onPublish(Object(Ratchet\\Wamp\\WampConnection), Object(Ratchet\\Wamp\\Topic), Array, Array, Array)\n#5 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/ServerProtocol.php(133): Ratchet\\Wamp\\TopicManager->onPublish(Object(Ratchet\\Wamp\\WampConnection), 'chat/90/e4de45f...', Array, Array, Array)\n#6 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Wamp/WampServer.php(41): Ratchet\\Wamp\\ServerProtocol->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#7 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Session/SessionProvider.php(94): Ratchet\\Wamp\\WampServer->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#8 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/WebSocket/Version/RFC6455.php(202): Ratchet\\Session\\SessionProvider->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '[7,\"chat/90/e4d...')\n#9 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(96): Ratchet\\WebSocket\\Version\\RFC6455->onMessage(Object(Ratchet\\WebSocket\\Version\\RFC6455\\Connection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#10 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(53): Ratchet\\WebSocket\\WsServer->onMessage(Object(Ratchet\\Server\\IoConnection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#11 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(113): Ratchet\\Http\\HttpServer->onMessage(Object(Ratchet\\Server\\IoConnection), '\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...')\n#12 [internal function]: Ratchet\\Server\\IoServer->handleData('\\x81\\xC4+(\\x82\\xEDp\\x1F\\xAE\\xCFH@\\xE3\\x99\\x04...', Object(React\\Socket\\Connection))\n#13 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)\n#14 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/socket/src/Connection.php(15): Evenement\\EventEmitter->emit('data', Array)\n#15 [internal function]: React\\Socket\\Connection->handleData(Resource id #485, Object(React\\EventLoop\\StreamSelectLoop))\n#16 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/event-loop/StreamSelectLoop.php(227): call_user_func(Array, Resource id #485, Object(React\\EventLoop\\StreamSelectLoop))\n#17 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/react/event-loop/StreamSelectLoop.php(201): React\\EventLoop\\StreamSelectLoop->waitForStreamActivity(5000000)\n#18 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/Type/WebSocketServer.php(192): React\\EventLoop\\StreamSelectLoop->run()\n#19 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Server/EntryPoint.php(48): Gos\\Bundle\\WebSocketBundle\\Server\\Type\\WebSocketServer->launch()\n#20 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/gos/web-socket-bundle/Command/WebsocketServerCommand.php(51): Gos\\Bundle\\WebSocketBundle\\Server\\EntryPoint->launch(NULL)\n#21 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(257): Gos\\Bundle\\WebSocketBundle\\Command\\WebsocketServerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(882): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(Gos\\Bundle\\WebSocketBundle\\Command\\WebsocketServerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#24 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#25 /Applications/XAMPP/xamppfiles/htdocs/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#26 /Applications/XAMPP/xamppfiles/htdocs/app/app/console(27): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput))\n#27 {main}"} 
```
1. Did you add automatic brodcast message that we send to the websocket? Can I turn off it?

2. https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/SessionSetup.md
```
            if(false !== $this->getCurrentUser($subscriber) && 'user2' === $this->getCurrentUser($subscriber)->getUsername){
```

Isn't getUsername a method? getUsername()

**Comment by ProPheT777** [comment]
1. By default broadcast function send to all subscriber of channel. (you can deal with include, exclude parameter to do what you want)
2. Nice catch, yes it's getUsername()

**Comment by ProPheT777** [comment]
typo was fixed in the last commit ;)
