### ISSUE TITLE
Call to undefined method setArgument()

### ISSUE THREAD

**Issue by jbbrunsveld** [GeniusesOfSymfony/WebSocketBundle#309]
Hi,
Today I ran an composer update and received version 1.8.12 (came from 1.8.11) which gives a major bug with Symfony 2.8.The class PingableDriverCompilerPass calls:

````
            $periodicPingDefinition = $container->getDefinition('gos_web_socket.pdo.periodic_ping');
            $periodicPingDefinition->setArgument(0, $pdoReference);
````
````
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\DependencyInjection\Definition::setArgument() in /var/www/jifeline/vendor/gos/web-socket-bundle/DependencyInjection/CompilerPass/PingableDriverCompilerPass.php:37
Stack trace:
#0 /var/www/jifeline/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(102): Gos\Bundle\WebSocketBundle\DependencyInjection\CompilerPass\PingableDriverCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /var/www/jifeline/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(587): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /var/www/jifeline/app/bootstrap.php.cache(2767): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /var/www/jifeline/app/bootstrap.php.cache(2542): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /var/www/jifeline/vendor/symfony/symfony/ in /var/www/jifeline/vendor/gos/web-socket-bundle/DependencyInjection/CompilerPass/PingableDriverCompilerPass.php on line 37
````

But the setArgument function does simply not exist (as setArguments does) in this version of Symfony. Only the latest 3.5 version contains this method. 

I tried to use setArguments and that seems to work:

````
            $periodicPingDefinition->setArguments([0, $pdoReference]);

````

**Comment by stevro** [comment]
@jbbrunsveld , any solution on this, beside upgrading to symfony 3 ?
