### ISSUE TITLE
websocket speed , php server crash

### ISSUE THREAD

**Issue by ma-gu-16** [GeniusesOfSymfony/WebSocketBundle#442]
hi there, 

ive been running symfony 4.3, all configured. i use websocket with client auth. and pdo session share. 
if i start the websocket. works well. i open the website, connection succesfull and in the logs the user is correct auth. 

next i just press f5 to reload the webpage.... 
```

after i reload the website is loading over and over and over until it complete crashes : like: Internal Server Error
both on apache and nginx. 
and i have no access anymore, and cant reload the page. 
```

solution i have to quit or exit the websocket. after i can open the website normal. 

if i start the websocket again, same thing. first connection succesfull, second reload, server crash. 
seems like an super endless loop or memory fail. 

any one some hints, or ways to figure it out ? 
thank you

**Comment by ma-gu-16** [comment]
after a while i figured out some logs 


```
[13-Sep-2021 13:49:03 Etc/GMT-1] PHP Warning:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction in x123vendor\symfony\http-foundation\Session\Storage\Handler\PdoSessionHandler.php:630
Stack trace:
#0 x123vendor\symfony\http-foundation\Session\Storage\Handler\PdoSessionHandler.php(630): PDOStatement->execute()
#1 x123vendor\symfony\http-foundation\Session\Storage\Handler\AbstractSessionHandler.php(106): Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler->doRead('bc70655a8fdcda1...')
#2 x123vendor\symfony\http-foundation\Session\Storage\Handler\PdoSessionHandler.php(284): Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler->read('bc70655a8fdcda1...')
#3 x123vendor\symfony\http-foundation\Session\Storage\Handler\AbstractSessionHandler.php(73): Symfony\Component\Http in x123vendor\symfony\http-foundation\Session\Storage\Handler\PdoSessionHandler.php on line 630
```

**Comment by ma-gu-16** [comment]
fixed it.  set the LOCK mode. 
https://symfony.com/doc/4.4/session/database.html

```
services.yaml
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(DATABASE_URL)%'
      - { db_table: 'symfony_sessions', lock_mode: 0 }
```
